spin_version = "1"
authors = ["Abilio Almeida Eiroa <aabilio@gmail.com>"]
description = "This is a simple app to test spin with Typescript"
name = "spin-ts-test"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-ts-test"
source = "target/spin-http-js.wasm"
exclude_files = ["**/node_modules"]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
